# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Leonardo Dionizio
email: leodionizio13@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Desenvolvedor web front-end, atualmente realizo meus trabalhos na
  <a href="http://focussp.com.br" target="_blank">Focus Desenvolvimento</a>, estudante de Análise e Desenvolvimento de Sistemas na
  <a href="http://www.fatectq.edu.br/" target="_blank">FatecTq</a> e apaixonado por desafios...
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: jekyllrb
github_username:  jekyll
linkedin_username: alguem
google_username: alguem2

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
collections:
  projects:
    output: true
    permalink: /projects/:path
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
